### ISSUE TITLE
UZIP version

### ISSUE THREAD

**Issue by yegor-pelykh** [TomasHubelbauer/esm-uzip-js#1]
Hi!
It is important for me to know on what version of `UZIP` the current version of `uzip-module` was made?
Is it based on the LATEST version of `UZIP` (`0.20201231.0`)?
Or any of the previous ones?

**Comment by TomasHubelbauer** [comment]
There is a GitHub Action that used to run and update the repository automatically to make sure it was always built against latest UZIP:
https://github.com/TomasHubelbauer/esm-uzip-js/blob/main/.github/workflows/update.yml

I turned it off because it was eating into my monthly quota for Actions too much.

The last time it was was in 2021:
https://github.com/TomasHubelbauer/esm-uzip-js/commit/8127668be72554c91e420da5b4ef8b5669b63fcc

So this repository is currently built against the UZIP version from that time.

All this repo does is to add `export default UZIP` at the end of the UZIP file, so if you want it for latest, do that manually for latest.

**Comment by TomasHubelbauer** [comment]
This is documented in the readme:
https://github.com/TomasHubelbauer/esm-uzip-js?tab=readme-ov-file#how-does-it-work--is-it-stale
